import AuthProvider from "@/components/Admin/Provider";
import { Provider as JotaiProvider } from 'jotai';

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <JotaiProvider>
          {children}
          </JotaiProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
