import type { Metadata } from "next";

import "../globals.css";
import { Inter as FontSans } from "next/font/google";

import { cn } from "@/lib/utils";
const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="light">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable,
        )}
      >
        <main className="min-h-screen flex flex-col items-center justify-center">
          <div className="w-full rounded-2xl border px-6 py-10 xs:px-8 md:p-12 lg:px-16 max-w-[650px] mx-auto bg-white shadow">
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
